export const EMPLOYEE_RESET = "EMPLOYEE_RESET";
export const EMPLOYEE_GET_STARTED = "EMPLOYEE_GET_STARTED";
export const EMPLOYEE_GET_FINISHED = "EMPLOYEE_GET_FINISHED";
export const EMPLOYEE_GET_ERROR = "EMPLOYEE_GET_ERROR";
